### ISSUE TITLE
add method to core/Http/URL to handle query string parameters

### ISSUE THREAD

**Issue by casti2525** [cogentParadigm/Starbug#106]
Is it possible to add a second parameter for $this->redirect($url, $params) to hand query string parameters. I currently had to use http_build_query() to append my parameters to my custom url.

**Comment by cogentParadigm** [comment]
closing since Starbug\Http\Url has now been replaced with PSR-7. If you feel additional tooling is needed on top of PSR-7, feel free to open an issue on https://github.com/cogentParadigm/starbug-http
