### ISSUE TITLE
Database Schemer Using Long Index Names

### ISSUE THREAD

**Issue by rgraves1989** [cogentParadigm/Starbug#83]
It is possible to attempt to create an index via 'sb migrate' that is too many characters in length, this is handled by the Schemer class. Most DBRMS's limits the index names at 30 characters, so I did a quick update to Schemer.php, updating usages of the index name to 30 characters via the substr method. A quick re-run of the migration and things were working again.

**Comment by cogentParadigm** [comment]
This is resolved via integration with doctrine which now generates a hash for the index name.
