### ISSUE TITLE
Files input has issues with multiple images.

### ISSUE THREAD

**Issue by piercers** [cogentParadigm/Starbug#85]
When uploading multiple images, the grid would only show one image. Additionally, if the form was submitted and had errors, the input field would save the images to the files table, but a join between images and the entity was not created.

[This file](https://bitbucket.org/neonrain/art-cantina/src/0650519d3aecd70afbaf205aa04415b9debd969f/core/app/templates/form/input.php?at=dev) has possible fixes for the above issues.

**Comment by cogentParadigm** [comment]
9ea2959
