### ISSUE TITLE
File select widget returns '-~' even when size=1

### ISSUE THREAD

**Issue by casti2525** [cogentParadigm/Starbug#96]
great framework btw ... but this causes a constraint error on a single reference field even if it is nullable

**Comment by cogentParadigm** [comment]
https://github.com/cogentParadigm/Starbug/commit/a75e90ad6de20d19ade44670102e9c077cbd8398

See attached commit. I have removed the -~ notation entirely. Replacement is now the default and adding/removing only requires using + or - notation. eg.

```php
$this->store(["initiatives"` => "1,2"]); //this will replace with 1 and 2
$this->store(["initiatives" => "3,4"]); //this will replace with 3 and 4 (no more 1 and 2)
$this->store(["initiatives" => "+1"]); //this will add 1 (now 1, 3 and 4)
$this->store(["initiatives" => "-3"]); //this will remove 3 (1 and 4 remain)
```
